
(function(global){
'use strict';
const E=global.Algebra2Engine;
if(!E)throw Error('Algebra2Engine must load before Lesson 89.');
const {esc,math,pow,frac,root,display,panel,callout,choice,mono,letters,makeChoices}=E.helpers;

const topics = [
{id:'pattern',title:'A square is a product',short:'The plus pattern',intro:'A binomial has two terms. Squaring it means multiplying the entire binomial by itself—not just squaring each term.',body:
 `<p>In this lesson, <strong>standard forms</strong> are common algebra patterns worth recognizing. The first is the square of a sum:</p>${panel('(x + a)<sup>2</sup> = x<sup>2</sup> + 2ax + a<sup>2</sup>','Square the first term. Add twice the product. Add the square of the second term.')}
 <p>Distribute each term in the first factor to <em>both</em> terms in the second. There are four products; the two middle products combine.</p>`,
 steps:[['Write the square as a product.',math('(x + a)<sup>2</sup> = (x + a)(x + a)')],['Distribute all four products.',math('x · x + x · a + a · x + a · a = x<sup>2</sup> + ax + ax + a<sup>2</sup>')],['Combine the like terms.',math('ax + ax = 2ax')+'; so the result is '+math('x<sup>2</sup> + 2ax + a<sup>2</sup>')+'.']],
 after:`<p>The letters can change without changing the pattern:</p>${panel('(x + b)<sup>2</sup> = x<sup>2</sup> + 2bx + b<sup>2</sup><br>(x + c)<sup>2</sup> = x<sup>2</sup> + 2cx + c<sup>2</sup><br>(x + y)<sup>2</sup> = x<sup>2</sup> + 2xy + y<sup>2</sup>')}${callout('A useful distinction','Expanding turns a product into a sum. Factoring reverses that process.')}`,
 mini:{prompt:'Which expression is equivalent to '+math('(x + 2)<sup>2</sup>')+'?',options:['x<sup>2</sup> + 4','x<sup>2</sup> + 4x + 4','x<sup>2</sup> + 2x + 4'],correct:1,explain:'The middle term is 2 · x · 2 = 4x, and the last term is 2² = 4.'}},
{id:'minus',title:'What changes with a minus?',short:'The minus pattern',intro:'The middle term changes sign. The last term stays positive because a negative times a negative is positive.',body:
 `${panel('(x − a)<sup>2</sup> = x<sup>2</sup> − 2ax + a<sup>2</sup>','A squared difference still has three terms after expansion.')}
 <p>Compare the two patterns: the first and last terms are squares in both. The sign between the original terms determines the sign of the middle term.</p>`,
 steps:[['Write both factors.',math('(x − a)<sup>2</sup> = (x − a)(x − a)')],['Multiply every pair.',math('x<sup>2</sup> − ax − ax + a<sup>2</sup>')],['Combine the middle terms.',math('x<sup>2</sup> − 2ax + a<sup>2</sup>')+' because '+math('−ax − ax = −2ax')+'.']],
 after:`${panel('(x − b)<sup>2</sup> = x<sup>2</sup> − 2bx + b<sup>2</sup><br>(x − c)<sup>2</sup> = x<sup>2</sup> − 2cx + c<sup>2</sup><br>(x − y)<sup>2</sup> = x<sup>2</sup> − 2xy + y<sup>2</sup>')}${callout('Do not lose the middle term',math('(x − a)<sup>2</sup>')+' is not '+math('x<sup>2</sup> − a<sup>2</sup>')+'. The latter factors as '+math('(x + a)(x − a)')+', which has different factors.')}
 <div id="pattern-lab"></div>`,
 mini:{prompt:'Expand '+math('(m − 3)<sup>2</sup>')+'.',options:['m<sup>2</sup> − 9','m<sup>2</sup> − 6m − 9','m<sup>2</sup> − 6m + 9'],correct:2,explain:'The middle term is −2 · m · 3 = −6m. The final term is (−3)(−3) = +9.'}},
{id:'factor',title:'Run the pattern backward',short:'Factoring & one variable',intro:'A perfect-square trinomial is the expanded form of a squared binomial. To factor it, recognize the squares and check the middle term.',body:
 `<p>First find the square roots of the first and last terms. Then check that the middle term is <strong>twice their product</strong>. Its sign tells you whether the binomial contains a plus or a minus.</p>${panel('u<sup>2</sup> + 2uv + v<sup>2</sup> = (u + v)<sup>2</sup><br>u<sup>2</sup> − 2uv + v<sup>2</sup> = (u − v)<sup>2</sup>')}`,
 steps:[['Recognize the outside squares.', 'In '+math('p<sup>2</sup> − 2pq + q<sup>2</sup>')+', the first and last terms are squares of '+math('p')+' and '+math('q')+'.'],['Verify the middle term.',math('2 · p · q = 2pq')+'. It is subtracted, so use a minus inside the binomial.'],['Write the factors.',math('p<sup>2</sup> − 2pq + q<sup>2</sup> = (p − q)<sup>2</sup> = (p − q)(p − q)')+'.']],
 after:`<h3>It works with one variable, too</h3><p>A number can fill the role of the second term. For example:</p>${panel('(x + 3)<sup>2</sup> = x<sup>2</sup> + 6x + 9<br>(x + 4)<sup>2</sup> = x<sup>2</sup> + 8x + 16<br>(x + 5)<sup>2</sup> = x<sup>2</sup> + 10x + 25')}${callout('Outside squares alone are not enough',math('x<sup>2</sup> + 7x + 9')+' is not '+math('(x + 3)<sup>2</sup>')+'. The middle term would need to be '+math('6x')+', not '+math('7x')+'.')}`,
 mini:{prompt:'Factor '+math('z<sup>2</sup> − 10z + 25')+'.',options:['(z − 5)<sup>2</sup>','(z + 5)<sup>2</sup>','(z − 5)(z + 5)'],correct:0,explain:'The outside terms are z² and 5²; the middle is −2 · z · 5. Use (z − 5)².'}},
{id:'powers',title:'Keep the exponent rules straight',short:'Powers & common factors',intro:'Multiplying monomials and raising a product to a power use different exponent rules. Factoring a common term reverses multiplication.',body:
 `<div class="split-two"><div class="tile">${math('x<sup>m</sup> · x<sup>n</sup> = x<sup>m+n</sup>')}<p>Same base, multiplied: <strong>add</strong> the exponents.</p></div><div class="tile">${math('(x<sup>m</sup>)<sup>n</sup> = x<sup>mn</sup>')}<p>A power of a power: <strong>multiply</strong> the exponents.</p></div></div>
 ${panel('(−2x<sup>3</sup>y)(−5x<sup>2</sup>y<sup>4</sup>) = 10x<sup>5</sup>y<sup>5</sup><br>(−3a<sup>2</sup>b)<sup>2</sup> = 9a<sup>4</sup>b<sup>2</sup>','Multiply the coefficients separately. A square applies to every factor inside the parentheses.')}`,
 steps:[['Find the greatest common factor.', 'For '+math('6x<sup>3</sup>y<sup>2</sup> − 9x<sup>2</sup>y')+', the coefficients share 3. The smallest shared exponents give '+math('x<sup>2</sup>y')+'.'],['Divide each term by the common factor.',math('6x<sup>3</sup>y<sup>2</sup> ÷ (3x<sup>2</sup>y) = 2xy')+' and '+math('−9x<sup>2</sup>y ÷ (3x<sup>2</sup>y) = −3')+'.'],['Write and check the factorization.',math('3x<sup>2</sup>y(2xy − 3)')+'. Distribute to recover the original expression.']],
 after:callout('Remember the coefficient',math('(−4a)<sup>2</sup> = 16a<sup>2</sup>')+', not '+math('−8a<sup>2</sup>')+'. The negative coefficient is squared, not multiplied by the exponent.'),
 mini:{prompt:'Simplify '+math('(−2x<sup>3</sup>)<sup>2</sup>')+'.',options:['−4x<sup>6</sup>','4x<sup>5</sup>','4x<sup>6</sup>'],correct:2,explain:'(−2)² = 4 and (x³)² = x⁶.'}},
{id:'science',title:'Make very large and small numbers readable',short:'Scientific notation',intro:'Scientific notation separates a number into a coefficient and a power of ten.',body:
 `${panel('a × 10<sup>n</sup>','For a positive number, 1 ≤ a < 10 and n is an integer. More generally, 1 ≤ |a| < 10.')}
 <p>Move the decimal point until the coefficient is at least 1 but less than 10. Count how many places it moved. A large original number uses a positive exponent; a tiny positive decimal uses a negative exponent.</p>`,
 steps:[['Start with a large number.',math('4,520,000 = 4.52 × 10<sup>6</sup>')+'. The decimal moved six places to the left.'],['Now try a small number.',math('0.00072 = 7.2 × 10<sup>−4</sup>')+'. The decimal moved four places to the right.'],['Check by rebuilding the number.',math('7.2 × 10<sup>−4</sup> = 7.2 ÷ 10,000 = 0.00072')+'.']],
 after:callout('Use the requested form',math('45.2 × 10<sup>5</sup>')+' has the same value as '+math('4.52 × 10<sup>6</sup>')+', but only the second is normalized scientific notation. The app gives you separate coefficient and exponent boxes.'),
 mini:{prompt:'Write 0.0000068 in scientific notation.',options:['6.8 × 10<sup>6</sup>','6.8 × 10<sup>−6</sup>','68 × 10<sup>−7</sup>'],correct:1,explain:'Move the decimal six places to the right to get 6.8. The original number is small, so the exponent is −6.'}},
{id:'geometry',title:'Read coordinates with confidence',short:'Distance, lines & circles',intro:'The review exercises use three coordinate ideas: distance between points, horizontal or vertical lines, and the standard equation of a circle.',body:
 `${panel('d = '+root('(x<sub>2</sub> − x<sub>1</sub>)<sup>2</sup> + (y<sub>2</sub> − y<sub>1</sub>)<sup>2</sup>'),'This is the Pythagorean theorem applied to horizontal and vertical changes.')}
 <div class="split-two"><div class="tile">${math('y = c')}<p><strong>Horizontal:</strong> the y-coordinate stays fixed. Its slope is 0.</p></div><div class="tile">${math('x = c')}<p><strong>Vertical:</strong> the x-coordinate stays fixed. Its slope is undefined.</p></div></div>`,
 steps:[['Subtract the coordinates.', 'For points '+math('(1, 2)')+' and '+math('(4, 6)')+', the horizontal change is 3 and the vertical change is 4.'],['Square and add.',math('d<sup>2</sup> = 3<sup>2</sup> + 4<sup>2</sup> = 9 + 16 = 25')+'.'],['Take the nonnegative square root.',math('d = '+root('25')+' = 5')+'. Distance is not negative.']],
 after:`<h3>Center and radius of a circle</h3>${panel('(x − h)<sup>2</sup> + (y − k)<sup>2</sup> = r<sup>2</sup>','The center is (h, k). The radius is r, not r². Here r is positive for a nondegenerate circle.')}
 <p>For example, ${math('(x − 2)<sup>2</sup> + (y + 3)<sup>2</sup> = 16')} has center ${math('(2, −3)')} and radius ${math('4')}. Read each parenthesis as “coordinate minus center.”</p>`,
 mini:{prompt:'The circle '+math('(x − 6)<sup>2</sup> + (y + 1)<sup>2</sup> = 9')+' has which center and radius?',options:['Center (−6, 1), radius 9','Center (6, −1), radius 3','Center (6, 1), radius 3'],correct:1,explain:'y + 1 means y − (−1), so the center is (6, −1). The radius is √9 = 3.'}},
{id:'equations',title:'Solve, then check the original equation',short:'Fractions & radicals',intro:'Keep equations balanced by applying the same operation to both sides. A candidate solution only counts if it works in the original equation.',body:
 `<h3>Equations with fractional coefficients</h3><p>Combine like terms or multiply the entire equation by a common denominator.</p>${panel(frac('x','3')+' + '+frac('x','6')+' = 4 &nbsp;→&nbsp; 2x + x = 24 &nbsp;→&nbsp; x = 8','Multiply every term by 6, then combine like terms.')}
 <h3>Equations with square roots</h3><p>Isolate the square root before squaring. For real numbers, a principal square root cannot be negative.</p>`,
 steps:[['Isolate the radical.', 'Start with '+math(root('2x')+' + 1 = 5')+'. Subtract 1: '+math(root('2x')+' = 4')+'.'],['Square both sides and solve.',math('2x = 16')+', so '+math('x = 8')+'.'],['Check in the original equation.',math(root('2 · 8')+' + 1 = '+root('16')+' + 1 = 5')+'. The candidate is valid.']],
 after:callout('Some equations have no real solution','An equation such as '+math(root('2x')+' = −4')+' has no real solution. Squaring would suggest '+math('x = 8')+', but checking shows that it does not satisfy the original equation. The answer boxes accept “no solution” when appropriate.'),
 mini:{prompt:'Does '+math(root('x')+' + 2 = 1')+' have a real solution?',options:['Yes, x = 1','No solution'],correct:1,explain:'Subtracting 2 gives √x = −1. A principal square root cannot be negative.'}},
{id:'formulas',title:'Substitute values—or isolate a letter',short:'Working with formulas',intro:'A formula may contain several variables. Sometimes the goal is a number; other times the goal is a new formula with a different letter alone.',body:
 `<h3>Substitution</h3><p>Replace every named variable with its given value, then follow the order of operations. If a problem specifies ${math('π = 3.14')}, use that value instead of a longer approximation.</p>${panel('S = 2πrh','For π = 3.14, r = 3, h = 2: S = 2 · 3.14 · 3 · 2 = 37.68.')}
 <h3>Rearranging a formula</h3><p>Undo the operations around the desired variable. To isolate a variable in a denominator, first multiply by that denominator.</p>`,
 steps:[['Clear the denominator.', 'From '+math('A = '+frac('B','c<sup>2</sup> + u<sup>2</sup>'))+', multiply to get '+math('A(c<sup>2</sup> + u<sup>2</sup>) = B')+'.'],['Isolate the square.',math('Au<sup>2</sup> = B − Ac<sup>2</sup>')+', then '+math('u<sup>2</sup> = '+frac('B − Ac<sup>2</sup>','A'))+'.'],['Take both square roots.',math('u = ±'+root(frac('B − Ac<sup>2</sup>','A')))+'. Algebraically, both signs must be considered.']],
 after:callout('Keep the domain restrictions','These rearrangements assume the quantities divided by are nonzero. For real solutions, the quantity under a square root must be nonnegative, and every candidate must still make the original formula defined. A physical length may use only the nonnegative root; these formula-choice exercises ask for both algebraic signs.'),
 mini:{prompt:'Solve '+math('u<sup>2</sup> = 49')+' over the real numbers.',options:['u = 7 only','u = ±7','u = ±49'],correct:1,explain:'Both 7² and (−7)² equal 49. Keep the ± sign when solving an unrestricted square equation.'}},
{id:'slope',title:'Measure rise over run',short:'Slope from a graph',intro:'The slope tells how much y changes for each unit increase in x. Use the same point order in the numerator and denominator.',body:
 `${panel('m = '+frac('y<sub>2</sub> − y<sub>1</sub>','x<sub>2</sub> − x<sub>1</sub>')+' = '+frac('vertical change','horizontal change'),'A line rising from left to right has positive slope. A line falling from left to right has negative slope.')}
 <p>Use the labeled coordinates rather than guessing from the drawing. A ratio of changes is more precise than visual steepness.</p>`,
 steps:[['Choose an order for the points.', 'Let '+math('(x<sub>1</sub>, y<sub>1</sub>) = (1, 2)')+' and '+math('(x<sub>2</sub>, y<sub>2</sub>) = (4, 4)')+'.'],['Compute both changes in that order.',math('Δy = 4 − 2 = 2')+' and '+math('Δx = 4 − 1 = 3')+'.'],['Divide rise by run.',math('m = '+frac('2','3'))+'. Reversing both orders also gives '+math(frac('−2','−3')+' = '+frac('2','3'))+'.']],
 after:`<div class="split-two"><div class="tile">${math('m = 0')}<p>Zero rise with nonzero run means a horizontal line.</p></div><div class="tile">${math('Δx = 0')}<p>A vertical line has zero run. Division by zero is undefined.</p></div></div>${callout('Subtract negative coordinates carefully',math('−4 − (−3) = −1')+'. The second minus changes the sign of the value being subtracted.')}`,
 mini:{prompt:'A line rises 3 units as you move 6 units to the right. What is its slope?',options:['2','−1/2','1/2'],correct:2,explain:'Slope is rise divided by run: 3/6 = 1/2.'}},
{id:'travel',title:'Turn a round trip into one equation',short:'Distance-rate-time problems',intro:'The outward and return trips use the same route, so their distances are equal—even when the speeds and travel times differ.',body:
 `${panel('distance = rate × time','Keep compatible units. Miles per hour × hours gives miles.')}
 <p>Let ${math('t')} be the outward travel time and ${math('T')} be the total travel time. The return time is ${math('T − t')}. If the two rates are ${math('v<sub>out</sub>')} and ${math('v<sub>back</sub>')}, then:</p>${panel('v<sub>out</sub>t = v<sub>back</sub>(T − t)','The two sides represent equal distances, not equal times.')}`,
 steps:[['Define the unknown.', 'Example: travel outward at 40 mph, return at 50 mph, total time 4.5 hours. Let '+math('t')+' be the outward time. Return time: '+math('4.5 − t')+'.'],['Set the distances equal.',math('40t = 50(4.5 − t)')+'. Distribute to get '+math('40t = 225 − 50t')+'.'],['Solve and check.',math('90t = 225')+', so '+math('t = 2.5')+' hours. Return time is 2 hours. Both distances are 100 miles.']],
 after:callout('Round only at the end','Keep the exact value while solving. For example, 2.875 rounds to 2.88 to the nearest hundredth. Check that both trip times are positive and add to the stated total.'),
 mini:{prompt:'A trip lasts 5 hours altogether. If the outward trip takes t hours, how long is the return trip?',options:['5 + t hours','5 − t hours','5t hours'],correct:1,explain:'Outward time + return time = total time, so return time = 5 − t.'}}
];



const DEFAULT_SOURCE = {
 q11:{c1:-3,c2:-6,x1:3,y1:5,z1:2,x2:2,y2:3,z2:1,confirmed:true},
 q12:{c:-4,a:5,b:2,cExp:3,power:2,confirmed:true},
 q16:{coefficient:9,add:5,rhs:11,confirmed:true}
};
// Confirmed from User's close-ups supplied October 2, 2026. These values and
// the printed A-E choices are fixed lesson content, not editable quiz settings.
Object.values(DEFAULT_SOURCE).forEach(Object.freeze);
Object.freeze(DEFAULT_SOURCE);
const clone=o=>JSON.parse(JSON.stringify(o));
const Q = (id,section,label,skill,type,prompt,rest) => ({id,section,label,skill,type,prompt,...rest});
function buildQuestions(){
 const cfg=DEFAULT_SOURCE;
 const q=[];
 q.push(Q('p-a','practice','a','Perfect-square factoring','mc','Select the factored form of the expression.'+display('x<sup>2</sup> + 2bx + b<sup>2</sup>'),{
 page:434,choices:makeChoices(['(x + b)<sup>2</sup>','(x − b)<sup>2</sup>','(x + b)(x − b)','(x<sup>2</sup> + b<sup>2</sup>)<sup>2</sup>','2(x + b)<sup>2</sup>']),correct:0,answerHTML:'A. (x + b)<sup>2</sup>',answerText:'A. (x + b)^2',lesson:'factor',
 guide:['Identify the square roots of the first and last terms.','Check whether twice their product matches the middle term.','Use the middle sign to choose the binomial.'],hints:['The outside terms are x² and b².','Twice the product of x and b is 2bx.','The middle term is added, so the two terms inside the binomial are added.'],
 solution:['The first and last terms are squares of x and b.','The middle term is +2bx, twice the product of those terms.','Therefore '+math('x<sup>2</sup> + 2bx + b<sup>2</sup> = (x + b)<sup>2</sup>')+'.'],check:'Expanding (x + b)(x + b) returns the original trinomial.'}));
 q.push(Q('p-b','practice','b','Perfect-square factoring','mc','Select the factored form of the expression.'+display('y<sup>2</sup> − 2ay + a<sup>2</sup>'),{
 page:434,choices:makeChoices(['(ay + 1)<sup>2</sup>','(y + 1)(y + a)','2(y + a)<sup>2</sup>','(y − a)<sup>2</sup>','(y + a)<sup>2</sup>']),correct:3,answerHTML:'D. (y − a)<sup>2</sup>',answerText:'D. (y - a)^2',lesson:'factor',guide:['Identify both square terms.','Check the magnitude and sign of the middle term.','Write a squared binomial.'],hints:['The outside terms are the squares of y and a.','The middle term is −2 · y · a.','A negative middle term means a minus inside the squared binomial.'],solution:['The square roots of the outside terms are y and a.','The middle term is −2ay, so use a minus.','The factorization is '+math('(y − a)<sup>2</sup>')+'.'],check:'(y − a)(y − a) = y² − ay − ay + a².'}));
 q.push(Q('p-c','practice','c','Expanding a squared difference','mc','Select the simplified form of the expression.'+display('(r − t)<sup>2</sup>'),{
 page:435,choices:makeChoices(['2r − 2t','−2rt','r<sup>2</sup> − 2rt + t<sup>2</sup>','r<sup>2</sup> − t<sup>2</sup>','r<sup>2</sup> + 2rt + t<sup>2</sup>']),correct:2,answerHTML:'C. r<sup>2</sup> − 2rt + t<sup>2</sup>',answerText:'C. r^2 - 2rt + t^2',lesson:'minus',guide:['Square the first term.','Subtract twice the product of the two terms.','Add the square of the second term.'],hints:['Use (u − v)² = u² − 2uv + v².','The middle term is −2rt.','The last term is positive: (−t)(−t) = t².'],solution:['Write '+math('(r − t)(r − t)')+'.','Distribute: '+math('r<sup>2</sup> − rt − rt + t<sup>2</sup>')+'.','Combine the middle terms to get '+math('r<sup>2</sup> − 2rt + t<sup>2</sup>')+'.']}));
 const lAnswer='l = ±'+root(frac('km − Fr<sup>2</sup>','F'));
 q.push(Q('p-d','practice','d','Rearranging a formula','mc','Which choice represents '+math('F = '+frac('km','r<sup>2</sup> + l<sup>2</sup>'))+' after it has been solved for '+math('l')+'?',{
 page:435,choices:makeChoices(['l = ±'+root(frac('km','Fr<sup>2</sup>')),'l = ±'+root('km − Fr<sup>2</sup>'),'l = ±'+root('km + Fr<sup>2</sup>'),lAnswer,'l = '+frac('km − Fr<sup>2</sup>','2F')]),correct:3,answerHTML:'D. '+lAnswer,answerText:'D. l = ±sqrt((km - Fr^2)/F)',lesson:'formulas',guide:['Multiply by the original denominator.','Move the r² term to the other side.','Divide to isolate l², then take both square roots.'],hints:['Multiplying by r² + l² gives F(r² + l²) = km.','After distributing and subtracting: Fl² = km − Fr².','Divide the entire right side by F before taking square roots.'],solution:[math('F(r<sup>2</sup> + l<sup>2</sup>) = km')+'.',math('Fr<sup>2</sup> + Fl<sup>2</sup> = km')+', so '+math('Fl<sup>2</sup> = km − Fr<sup>2</sup>')+'.',math('l<sup>2</sup> = '+frac('km − Fr<sup>2</sup>','F'))+'.',math(lAnswer)+'.'],check:'Assume F ≠ 0, require a nonnegative radicand for real answers, and keep the original denominator nonzero.'}));
 q.push(Q('p-e','practice','e','Distance, rate, and time','trip',
 '<p>Gary traveled from his home to the stadium at a speed of 55 mph. He traveled the same route on his way back home, but on the return trip his speed was 65 mph. If, altogether, Gary spent a total of 3 hours on the road, how many hours did the trip to the stadium take?</p><p><strong>Translate the situation into an equation, then solve. Round the time to the nearest hundredth (two decimal places).</strong></p>',{
 page:435,choices:makeChoices(['55t = 65(3 − t)','65t = 55(3 − t)','55t + 65t = 3','55t = 65(3 + t)','55(3 − t) = 65(3 − t)']),correct:0,fields:[{key:'time',label:'Time to the stadium',suffix:'hours',placeholder:'e.g., 2.75',value:1.63,tolerance:0.00000001}],define:'Let t be the number of hours for the trip from home to the stadium.',answerHTML:'55t = 65(3 − t); &nbsp; t ≈ 1.63 hours',answerText:'55t = 65(3 - t); t = 1.625 ≈ 1.63 hours',lesson:'travel',guide:['Let t represent time to the stadium. Write the return time in terms of t.','Use distance = rate × time for each direction.','Set the distances equal, solve, and round only at the end.'],hints:['The return trip takes 3 − t hours.','The outward distance is 55t miles. The return distance is 65(3 − t) miles.','Expand the right side and gather the t terms: 120t = 195.'],solution:['The return trip takes '+math('3 − t')+' hours.','Equal distances give '+math('55t = 65(3 − t)')+'.',math('55t = 195 − 65t')+', so '+math('120t = 195')+'.',math('t = '+frac('195','120')+' = 1.625')+' hours. Rounded to the nearest hundredth, this is <strong>1.63 hours</strong>.'],check:'Using the unrounded times: 55 × 1.625 = 89.375 miles and 65 × 1.375 = 89.375 miles. The times total 3 hours.',answerHelp:'Choose an equation and enter a time rounded to two decimal places. The exact value alone does not satisfy the requested rounding.'}));
 q.push(Q('s-1','problem','1','Recognizing standard forms','mc','“Standard forms” are expressions that come up so often that it is smart to memorize them.',{page:435,choices:[choice('T','True'),choice('F','False')],correct:0,answerHTML:'True',answerText:'True',lesson:'pattern',hints:['Here “standard” means common or frequently occurring.'],guide:['Recall how this lesson uses the term “standard forms.”'],solution:['The statement is <strong>true</strong> in the vocabulary of this lesson. Recognizing frequently used algebra patterns can make expanding and factoring more efficient.']}));
 q.push(Q('s-2','problem','2','Recognizing standard forms','mc','Two of the most common standard forms are '+math('(x + a)<sup>2</sup>')+', which equals '+math('x<sup>2</sup> + 2ax + a<sup>2</sup>')+', and '+math('(x − a)<sup>2</sup>')+', which equals '+math('x<sup>2</sup> − 2ax + a<sup>2</sup>')+'.',{
 page:435,choices:[choice('T','True'),choice('F','False')],correct:0,answerHTML:'True',answerText:'True',lesson:'pattern',hints:['Compare the middle terms. The sign inside the binomial determines the middle sign.'],guide:['Check the plus identity.','Check the minus identity, including the sign of the last term.'],solution:['The statement is <strong>true</strong>. In each expansion, the outside terms are squares and the middle term is twice the product of the terms inside the binomial.','The squared difference has a negative middle term but a positive last term.']}));
 q.push(Q('s-3','problem','3','Scientific notation','scientific','Rewrite the number in scientific notation.'+display('29,106,000'),{
 page:435,fields:[{key:'coefficient',label:'Coefficient',placeholder:'e.g., 3.42',value:2.9106,tolerance:1e-10},{key:'exponent',label:'Exponent of 10',placeholder:'e.g., 5',value:7,tolerance:0}],answerHTML:'2.9106 × 10<sup>7</sup>',answerText:'2.9106 × 10^7',lesson:'science',guide:['Place the decimal so the coefficient is at least 1 and less than 10.','Count the decimal places moved.','Choose the sign of the exponent and reconstruct the original number.'],hints:['The normalized coefficient begins with 2.','Move the decimal seven places left.','The original number is greater than 1, so the exponent is positive.'],solution:['Moving the decimal gives the coefficient '+math('2.9106')+'.','The decimal moved 7 places left.','Therefore '+math('29,106,000 = 2.9106 × 10<sup>7</sup>')+'.'],check:'2.9106 × 10,000,000 = 29,106,000.',answerHelp:'Use the boxes to write coefficient × 10^exponent. The coefficient must be at least 1 and less than 10.'}));
 q.push(Q('s-4','problem','4','Scientific notation','scientific','Rewrite the number in scientific notation.'+display('0.000000005'),{
 page:435,fields:[{key:'coefficient',label:'Coefficient',placeholder:'e.g., 3.42',value:5,tolerance:1e-10},{key:'exponent',label:'Exponent of 10',placeholder:'e.g., −5',value:-9,tolerance:0}],answerHTML:'5 × 10<sup>−9</sup>',answerText:'5 × 10^-9',lesson:'science',guide:['Move the decimal to make a coefficient between 1 and 10.','Count carefully: include the final move past the nonzero digit.','Decide whether the exponent should be positive or negative.'],hints:['The coefficient is a single nonzero digit.','It takes nine decimal places to get from 0.000000005 to 5.','A small positive decimal uses a negative power of ten.'],solution:['The coefficient is '+math('5')+'.','Move the decimal nine places to the right.','The exponent is −9: '+math('0.000000005 = 5 × 10<sup>−9</sup>')+'.'],check:'5 ÷ 1,000,000,000 = 0.000000005.',answerHelp:'Use the boxes to write coefficient × 10^exponent. Include the minus sign when needed.'}));
 q.push(Q('s-5','problem','5','Distance between points','numeric','Find the distance between the points '+math('('+frac('1','2')+', 0)')+' and '+math('(5'+frac('1','2')+', 6)')+' on the coordinate plane.',{
 page:435,fields:[{key:'distance',label:'Distance',suffix:'units',placeholder:'sqrt(…), fraction, or decimal',value:Math.sqrt(61),tolerance:0.005}],answerHTML:root('61')+' ≈ 7.81 units',answerText:'sqrt(61) ≈ 7.81 units',lesson:'geometry',guide:['Compute the horizontal change using 5½ − ½.','Compute the vertical change.','Square both changes, add, and take the nonnegative square root.'],hints:['The horizontal change is 5.','The vertical change is 6.','Use d² = 5² + 6².'],solution:[math('Δx = 5.5 − 0.5 = 5')+' and '+math('Δy = 6 − 0 = 6')+'.',math('d = '+root('5<sup>2</sup> + 6<sup>2</sup>')+' = '+root('25 + 36')+' = '+root('61'))+'.','The exact answer is '+math(root('61'))+' units; to the nearest hundredth it is '+math('7.81')+' units.'],check:'Distance is nonnegative. 7.81² is approximately 61.',answerHelp:'Enter an exact answer such as sqrt(61), or round your decimal to the nearest hundredth. A mixed number such as 5 1/2 is also understood.'}));
 q.push(Q('s-6','problem','6','Horizontal and vertical lines','mc','Tell whether the line for '+math('y = −5')+' is horizontal or vertical.',{
 page:435,choices:[choice('H','Horizontal'),choice('V','Vertical')],correct:0,answerHTML:'Horizontal',answerText:'Horizontal',lesson:'geometry',guide:['Decide which coordinate stays fixed.','Think of the points (0, −5) and (2, −5).'],hints:['Every point has y-coordinate −5.','You can move left and right while keeping y fixed.'],solution:['The y-coordinate is always −5 while x can vary.','All such points form a <strong>horizontal line</strong>. Its slope is 0.']}));
 q.push(Q('s-7','problem','7','Center and radius','numeric','Tell the center and radius of the circle for the equation'+display('(x − 9)<sup>2</sup> + (y − 4)<sup>2</sup> = 25') ,{
 page:435,fields:[{key:'centerX',label:'Center: x-coordinate',placeholder:'x',value:9,tolerance:0},{key:'centerY',label:'Center: y-coordinate',placeholder:'y',value:4,tolerance:0},{key:'radius',label:'Radius',placeholder:'r',value:5,tolerance:0}],answerHTML:'Center (9, 4); radius 5',answerText:'Center (9, 4); radius 5',lesson:'geometry',guide:['Match the equation to (x − h)² + (y − k)² = r².','Read h and k from the subtractions.','Take the positive square root of the right-hand side for the radius.'],hints:['The circle form is (x − h)² + (y − k)² = r².','The numbers subtracted from x and y give the center.','25 is the radius squared, not the radius.'],solution:['Comparing with the circle form gives '+math('h = 9')+' and '+math('k = 4')+'.','Since '+math('r<sup>2</sup> = 25')+', the radius is '+math('r = 5')+'.','The center is <strong>(9, 4)</strong> and the radius is <strong>5</strong>.'],answerHelp:'Fill in all three boxes. This is one exercise, so all three parts must be correct together within two valid submissions to earn its point.'}));
 q.push(Q('s-8','problem','8','Factoring a common monomial','mc','Select the factored form of the expression.'+display('5x<sup>3</sup>y<sup>3</sup> − 10x<sup>2</sup>y<sup>2</sup>'),{
 page:435,choices:makeChoices(['5x<sup>2</sup>y<sup>2</sup>(xy − 2)','5x<sup>3</sup>y<sup>3</sup>(1 − 2xy)','5x<sup>2</sup>y<sup>2</sup>(xy − 5)','10x<sup>2</sup>y<sup>2</sup>(2xy − 1)','−5xy']),correct:0,answerHTML:'A. 5x<sup>2</sup>y<sup>2</sup>(xy − 2)',answerText:'A. 5x^2y^2(xy - 2)',lesson:'powers',guide:['Find the greatest common factor of the coefficients.','Use the smallest shared exponent for each variable.','Divide both original terms by the common factor.'],hints:['Both terms contain 5x²y².','The first term divided by 5x²y² is xy.','The second term divided by 5x²y² is −2.'],solution:['The greatest common monomial factor is '+math('5x<sup>2</sup>y<sup>2</sup>')+'.','Dividing the first term by it gives '+math('xy')+'; dividing the second term gives '+math('−2')+'.','The factored form is '+math('5x<sup>2</sup>y<sup>2</sup>(xy − 2)')+'.'],check:'Distribute the common factor to recover 5x³y³ − 10x²y².'}));
 q.push(Q('s-9','problem','9','Perfect-square factoring','mc','Select the factored form of the expression.'+display('x<sup>2</sup> + 2cx + c<sup>2</sup>'),{
 page:435,choices:makeChoices(['2(x + c)<sup>2</sup>','(x − c)<sup>2</sup>','(x + c)<sup>2</sup>','(x + c)(x − c)','(x<sup>2</sup> + c<sup>2</sup>)<sup>2</sup>']),correct:2,answerHTML:'C. (x + c)<sup>2</sup>',answerText:'C. (x + c)^2',lesson:'factor',guide:['Identify the outside squares.','Match the middle term to twice the product.','Choose the sign.'],hints:['The terms to put inside the binomial are x and c.','The middle term is +2cx.'],solution:['The outside terms are '+math('x<sup>2</sup>')+' and '+math('c<sup>2</sup>')+'.','The positive middle term is twice the product of x and c.','The factorization is '+math('(x + c)<sup>2</sup>')+'.']}));
 q.push(Q('s-10','problem','10','Perfect-square factoring','mc','Select the factored form of the expression.'+display('y<sup>2</sup> − 2by + b<sup>2</sup>'),{
 page:435,choices:makeChoices(['(by + 1)<sup>2</sup>','(y − b)<sup>2</sup>','(y + 1)(y + b)','(y + b)<sup>2</sup>','2(y + b)<sup>2</sup>']),correct:1,answerHTML:'B. (y − b)<sup>2</sup>',answerText:'B. (y - b)^2',lesson:'factor',guide:['Recognize y² and b² as squares.','Check the sign on 2by.'],hints:['This matches u² − 2uv + v².','A negative middle term uses a minus in the squared binomial.'],solution:['The first and last terms are squares of y and b.','Because the middle term is −2by, the expression factors as '+math('(y − b)<sup>2</sup>')+'.']}));
 const a=cfg.q11, sums=[a.x1+a.x2,a.y1+a.y2,a.z1+a.z2],prod=a.c1*a.c2;
 const q11correct=mono(prod,sums);
 // Exact printed choices in their original order (A-E).
 const q11Options=[mono(-9,[5,8,3]),mono(18,[6,15,2]),mono(-18,[5,8,3]),mono(-9,[1,2,1]),q11correct];
 q.push(Q('s-11','problem','11','Multiplying monomials','mc','Select the simplified form of the expression.'+display('('+mono(a.c1,[a.x1,a.y1,a.z1])+')('+mono(a.c2,[a.x2,a.y2,a.z2])+')'),{
 page:436,sourceKey:'q11',choices:makeChoices(q11Options),correct:4,answerHTML:'E. '+q11correct,answerText:'E. '+prod+'x^'+sums[0]+'y^'+sums[1]+'z^'+sums[2],lesson:'powers',guide:['Multiply the numerical coefficients.','For each variable, add the exponents from the two factors.','Combine the coefficient and powers into one monomial.'],hints:['The product of two negative coefficients is positive.','When multiplying powers with the same base, add the exponents.','Treat x, y, and z separately; an unwritten exponent is 1.'],solution:[math(`(${a.c1})(${a.c2}) = ${prod}`)+'.',math(`x<sup>${a.x1}</sup> · x<sup>${a.x2}</sup> = x<sup>${sums[0]}</sup>`)+'.',math(`y<sup>${a.y1}</sup> · y<sup>${a.y2}</sup> = y<sup>${sums[1]}</sup>`)+' and '+math(`z<sup>${a.z1}</sup> · z<sup>${a.z2}</sup> = z<sup>${sums[2]}</sup>`)+'.','The simplified result is '+math(q11correct)+'.'],check:'Multiply the coefficients: (−3)(−6) = 18. Add exponents for each base: x^(3+2), y^(5+3), z^(2+1). This gives 18x^5y^8z^3, choice E.'}));
 const b=cfg.q12,bExps=[b.a*b.power,b.b*b.power,b.cExp*b.power],bc=Math.pow(b.c,b.power);
 const q12correct=mono(bc,bExps,['a','b','c']);
 q.push(Q('s-12','problem','12','Power of a monomial','mc','Select the simplified form of the expression.'+display('('+mono(b.c,[b.a,b.b,b.cExp],['a','b','c'])+')<sup>'+b.power+'</sup>'),{
 page:436,sourceKey:'q12',choices:makeChoices([mono(16,[7,4,5],['a','b','c']),mono(-8,[25,4,9],['a','b','c']),q12correct,mono(16,[25,4,9],['a','b','c']),mono(-8,[10,4,6],['a','b','c'])]),correct:2,answerHTML:'C. '+q12correct,answerText:'C. '+bc+'a^'+bExps[0]+'b^'+bExps[1]+'c^'+bExps[2],lesson:'powers',guide:['Apply the outer power to the coefficient.','Multiply each inner exponent by the outer exponent.','Check the sign of the resulting coefficient.'],hints:['An outer power applies to every factor inside the parentheses.','Use (a^m)^n = a^(mn), not a^(m+n).','An even power of a negative coefficient is positive.'],solution:[math(`(${b.c})<sup>${b.power}</sup> = ${bc}`)+'.','Multiply the variable exponents by '+b.power+': '+math(`a<sup>${bExps[0]}</sup>, b<sup>${bExps[1]}</sup>, c<sup>${bExps[2]}</sup>`)+'.','The result is '+math(q12correct)+'.'],check:'Every factor is squared: (−4)^2 = 16, (a^5)^2 = a^10, (b^2)^2 = b^4, and (c^3)^2 = c^6. The result is choice C.'}));
 q.push(Q('s-13','problem','13','Expanding a squared sum','mc','Select the simplified form of the expression.'+display('(x + y)<sup>2</sup>'),{
 page:436,choices:makeChoices(['x<sup>2</sup> + xy + y<sup>2</sup>','2x<sup>2</sup> + 2y<sup>2</sup>','x<sup>2</sup> + 2xy + y<sup>2</sup>','2x + 2y','x<sup>2</sup> + y<sup>2</sup>']),correct:2,answerHTML:'C. x<sup>2</sup> + 2xy + y<sup>2</sup>',answerText:'C. x^2 + 2xy + y^2',lesson:'pattern',guide:['Square x.','Add twice the product of x and y.','Add the square of y.'],hints:['There are two xy products when you distribute.','Combine xy + xy into 2xy.'],solution:[math('(x + y)<sup>2</sup> = (x + y)(x + y)')+'.',math('x<sup>2</sup> + xy + xy + y<sup>2</sup> = x<sup>2</sup> + 2xy + y<sup>2</sup>')+'.']}));
 q.push(Q('s-14','problem','14','Expanding a squared difference','mc','Select the simplified form of the expression.'+display('(p − q)<sup>2</sup>'),{
 page:436,choices:makeChoices(['p<sup>2</sup> + 2pq + q<sup>2</sup>','p<sup>2</sup> − 2pq + q<sup>2</sup>','p<sup>2</sup> − q<sup>2</sup>','2p − 2q','−2pq']),correct:1,answerHTML:'B. p<sup>2</sup> − 2pq + q<sup>2</sup>',answerText:'B. p^2 - 2pq + q^2',lesson:'minus',guide:['Square each outer term.','Subtract twice their product.','Keep the last square positive.'],hints:['Use (u − v)² = u² − 2uv + v².','The middle term is −2pq, and the last term is +q².'],solution:[math('(p − q)(p − q) = p<sup>2</sup> − pq − pq + q<sup>2</sup>')+'.','Combining the middle terms gives '+math('p<sup>2</sup> − 2pq + q<sup>2</sup>')+'.']}));
 q.push(Q('s-15','problem','15','A linear equation with fractions','numeric','Solve the equation. List only valid solutions; write “no solution” if there are none.'+display(frac('1','2')+'x + '+frac('1','8')+'x = −1'),{
 page:436,fields:[{key:'x',label:'x =',placeholder:'fraction or decimal',value:-8/5,tolerance:1e-9}],answerHTML:'x = −'+frac('8','5')+' = −1.6',answerText:'x = -8/5 = -1.6',lesson:'equations',guide:['Use a common denominator, or multiply every term by 8.','Combine the x terms.','Isolate x and substitute it back into the original equation.'],hints:['Multiplying by 8 clears both denominators.','This gives 4x + x = −8.','Combine the left side and divide by the coefficient of x.'],solution:['Multiply each term by 8: '+math('4x + x = −8')+'.',math('5x = −8')+'.',math('x = −'+frac('8','5')+' = −1.6')+'.'],check:'(1/2)(−1.6) + (1/8)(−1.6) = −0.8 − 0.2 = −1.',answerHelp:'Enter a fraction, decimal, or “no solution.” Do not list values that fail the original equation.'}));
 const r=cfg.q16,rhsRoot=r.rhs-r.add,rx=rhsRoot<0?null:rhsRoot*rhsRoot/r.coefficient;
 const rAnswer=rx===null?'No solution':'x = '+(Number.isInteger(rx)?rx:Number(rx.toFixed(10)));
 q.push(Q('s-16','problem','16','A square-root equation','numeric','Solve the equation. List only valid solutions; write “no solution” if there are none.'+display(root(r.coefficient+'x')+' + '+r.add+' = '+r.rhs),{
 page:436,sourceKey:'q16',fields:[{key:'x',label:'x =',placeholder:'number or no solution',value:rx,tolerance:1e-8}],answerHTML:rAnswer,answerText:rAnswer,lesson:'equations',guide:['Isolate the square root.','Check whether the isolated square root would be negative.','If possible, square both sides, solve, and check in the original equation.'],hints:['Subtract the constant outside the square root from both sides.','A principal square root must be nonnegative.','Square only after isolating the radical, and check your candidate.'],solution:rx===null?[math(root(r.coefficient+'x')+' = '+rhsRoot)+'.','A principal square root cannot be negative, so the equation has <strong>no real solution</strong>.']:[math(root(r.coefficient+'x')+' = '+r.rhs+' − '+r.add+' = '+rhsRoot)+'.','Square both sides: '+math(r.coefficient+'x = '+(rhsRoot*rhsRoot))+'.','Divide by '+r.coefficient+': '+math('x = '+(Number.isInteger(rx)?rx:frac(rhsRoot*rhsRoot,r.coefficient)))+'.'],check:rx===null?'Squaring a negative right-hand side would introduce an extraneous candidate.':`Substitution gives √(${r.coefficient} × ${Number(rx.toFixed(8))}) + ${r.add} = ${rhsRoot} + ${r.add} = ${r.rhs}.`,answerHelp:'The radical covers 9x only; +5 is outside the square root. Enter a number, a fraction, or “no solution.”'}));
 q.push(Q('s-17','problem','17','Substitution into a formula','numeric','In the equation '+math('S = 2πrh')+', find the value of '+math('S')+' when '+math('π = 3.14')+', '+math('r = 5')+', and '+math('h = 4')+'.',{
 page:436,fields:[{key:'S',label:'S =',placeholder:'number',value:125.6,tolerance:1e-8}],answerHTML:'S = 125.6',answerText:'S = 125.6',lesson:'formulas',guide:['Replace π, r, and h with their stated values.','Multiply all four factors.','Use exactly 3.14 for π in this exercise.'],hints:['The product is 2 × 3.14 × 5 × 4.','You can group 2 × 5 × 4 first.'],solution:[math('S = 2 · 3.14 · 5 · 4')+'.',math('2 · 5 · 4 = 40')+'.',math('S = 3.14 · 40 = 125.6')+'.'],check:'Use the supplied approximation π = 3.14, not the calculator’s full π constant.'}));
 const hAnswer='h = ±'+root(frac('kq − Er<sup>2</sup>','E'));
 q.push(Q('s-18','problem','18','Rearranging a formula','mc','Which choice represents '+math('E = '+frac('kq','r<sup>2</sup> + h<sup>2</sup>'))+' after it has been solved for '+math('h')+'?',{
 page:436,choices:makeChoices(['h = '+frac('kq − Er<sup>2</sup>','2E'),hAnswer,'h = ±'+root('kq − Er<sup>2</sup>'),'h = ±'+root(frac('kq','Er<sup>2</sup>')),'h = ±'+root('kq + Er<sup>2</sup>')]),correct:1,answerHTML:'B. '+hAnswer,answerText:'B. h = ±sqrt((kq - Er^2)/E)',lesson:'formulas',guide:['Multiply by r² + h².','Distribute E and isolate the h² term.','Divide by E, then take both square roots.'],hints:['Multiplying gives E(r² + h²) = kq.','Subtract Er²: Eh² = kq − Er².','Divide the entire right-hand side by E before taking square roots.'],solution:[math('E(r<sup>2</sup> + h<sup>2</sup>) = kq')+'.',math('Eh<sup>2</sup> = kq − Er<sup>2</sup>')+'.',math('h<sup>2</sup> = '+frac('kq − Er<sup>2</sup>','E'))+'.',math(hAnswer)+'.'],check:'Assume E ≠ 0. For real answers the radicand must be nonnegative; keep the original denominator nonzero.'}));
 q.push(Q('s-19','problem','19','Slope from two points','numeric','Find the slope of line <strong>A</strong>. The labeled points on A are '+math('(−2, −3)')+' and '+math('(0, −4)')+'.',{
 page:436,graph:'A',fields:[{key:'slope',label:'Slope of A',placeholder:'fraction or decimal',value:-0.5,tolerance:1e-9}],answerHTML:'m<sub>A</sub> = −'+frac('1','2'),answerText:'Slope of A = -1/2',lesson:'slope',guide:['Choose the order (−2, −3) then (0, −4).','Subtract y-values and x-values in the same order.','Divide the change in y by the change in x.'],hints:['Slope is (y₂ − y₁)/(x₂ − x₁).','The vertical change is −4 − (−3).','The horizontal change is 0 − (−2).'],solution:[math('m = '+frac('−4 − (−3)','0 − (−2)'))+'.',math('m = '+frac('−1','2')+' = −0.5')+'.'],check:'Line A falls as x increases, so a negative slope makes sense.',answerHelp:'Enter an exact fraction or a decimal. Use a minus sign for a negative slope.'}));
 q.push(Q('s-20','problem','20','Slope from two points','numeric','Find the slope of line <strong>B</strong>. The labeled points on B are '+math('(2, 3)')+' and '+math('(5, 4)')+'.',{
 page:436,graph:'B',fields:[{key:'slope',label:'Slope of B',placeholder:'fraction or decimal',value:1/3,tolerance:0.0005}],answerHTML:'m<sub>B</sub> = '+frac('1','3'),answerText:'Slope of B = 1/3',lesson:'slope',guide:['Use (2, 3) as the first point and (5, 4) as the second.','Compute the vertical and horizontal changes.','Divide rise by run and simplify.'],hints:['The vertical change is 4 − 3.','The horizontal change is 5 − 2.','The line rises, so the slope should be positive.'],solution:[math('m = '+frac('4 − 3','5 − 2'))+'.',math('m = '+frac('1','3'))+'.'],check:'A rise of 1 unit over a run of 3 units is consistent with the drawing.',answerHelp:'A fraction is best. If using a decimal, give at least three decimal places (for example, 0.333 for one third).'}));
 q.push(Q('s-21','problem','21','Distance, rate, and time','trip',
 '<p>Dashell traveled from his home to his office at a speed of 60 mph. He traveled the same route on his way back home, but on the return trip his speed was 65 mph. If, altogether, Dashell spent a total of 4 hours on the road, how many hours did the trip to his office take?</p><p><strong>Translate the situation into an equation, then solve.</strong></p>',{
 page:436,choices:makeChoices(['65t = 60(4 − t)','60t + 65t = 4','60t = 65(4 − t)','60t = 65(4 + t)','60(4 − t) = 65(4 − t)']),correct:2,fields:[{key:'time',label:'Time to the office',suffix:'hours',placeholder:'fraction or decimal',value:2.08,tolerance:1e-9}],define:'Let t be the number of hours for the trip from home to the office.',answerHTML:'60t = 65(4 − t); &nbsp; t = 2.08 hours',answerText:'60t = 65(4 - t); t = 2.08 hours',lesson:'travel',guide:['Represent the return time as total time minus outward time.','Write one distance expression for each direction.','Set distances equal, solve, and check both trips.'],hints:['The return trip takes 4 − t hours.','The two distance expressions are 60t and 65(4 − t).','After expanding and combining, 125t = 260.'],solution:['Outward distance is '+math('60t')+' miles; return distance is '+math('65(4 − t)')+' miles.','Set them equal: '+math('60t = 65(4 − t)')+'.',math('60t = 260 − 65t')+', so '+math('125t = 260')+'.',math('t = '+frac('260','125')+' = 2.08')+' hours.'],check:'60 × 2.08 = 124.8 miles; the return takes 1.92 hours, and 65 × 1.92 = 124.8 miles. Total time: 4 hours.',answerHelp:'Choose the equation and enter the outward travel time in hours. Both parts are needed for this exercise.'}));
 return q;
}



function graphSVG(highlight){
 const X=x=>260+28*x,Y=y=>230-28*y;let grid='',nums='';
 for(let x=-7;x<=8;x++){grid+=`<line x1="${X(x)}" y1="34" x2="${X(x)}" y2="426" stroke="#e7e8df"/>`;if(x!==0&&x%2===0)nums+=`<text x="${X(x)}" y="249" text-anchor="middle">${x<0?'−'+Math.abs(x):x}</text>`;}
 for(let y=-7;y<=7;y++){grid+=`<line x1="64" y1="${Y(y)}" x2="484" y2="${Y(y)}" stroke="#e7e8df"/>`;if(y!==0&&y%2===0)nums+=`<text x="249" y="${Y(y)+4}" text-anchor="end">${y<0?'−'+Math.abs(y):y}</text>`;}
 const A=highlight==='A'?'#17685f':'#6c7472',B=highlight==='B'?'#17685f':'#6c7472';
 return `<figure class="graph-frame"><svg viewBox="0 0 560 470" role="img" aria-labelledby="graph-title graph-desc"><title id="graph-title">Lines A and B on a coordinate plane</title><desc id="graph-desc">Line A goes through (−2, −3) and (0, −4). Line B goes through (2, 3) and (5, 4). Line ${highlight} is highlighted. Exact point coordinates are also stated above the graph.</desc><defs><marker id="axis-arrow" markerWidth="8" markerHeight="8" refX="6" refY="4" orient="auto-start-reverse"><path d="M1,1 L6,4 L1,7" fill="none" stroke="#263b40" stroke-width="1.5"/></marker><marker id="a-arrow" markerWidth="8" markerHeight="8" refX="6" refY="4" orient="auto-start-reverse"><path d="M1,1 L6,4 L1,7" fill="none" stroke="${A}" stroke-width="1.5"/></marker><marker id="b-arrow" markerWidth="8" markerHeight="8" refX="6" refY="4" orient="auto-start-reverse"><path d="M1,1 L6,4 L1,7" fill="none" stroke="${B}" stroke-width="1.5"/></marker></defs>${grid}<g stroke="#263b40" stroke-width="1.8"><line x1="58" y1="230" x2="498" y2="230" marker-start="url(#axis-arrow)" marker-end="url(#axis-arrow)"/><line x1="260" y1="435" x2="260" y2="25" marker-start="url(#axis-arrow)" marker-end="url(#axis-arrow)"/></g><g fill="#62736e" font-family="system-ui,sans-serif" font-size="11">${nums}</g><g font-family="Georgia,serif" font-size="18" fill="#263b40"><text x="508" y="234">x</text><text x="271" y="26">y</text></g><line x1="${X(-6.5)}" y1="${Y(-.75)}" x2="${X(6)}" y2="${Y(-7)}" stroke="${A}" stroke-width="3.3" marker-start="url(#a-arrow)" marker-end="url(#a-arrow)"/><line x1="${X(-5)}" y1="${Y(2/3)}" x2="${X(7.4)}" y2="${Y(4.8)}" stroke="${B}" stroke-width="3.3" marker-start="url(#b-arrow)" marker-end="url(#b-arrow)"/><g fill="${A}"><circle cx="${X(-2)}" cy="${Y(-3)}" r="5"/><circle cx="${X(0)}" cy="${Y(-4)}" r="5"/></g><g fill="${B}"><circle cx="${X(2)}" cy="${Y(3)}" r="5"/><circle cx="${X(5)}" cy="${Y(4)}" r="5"/></g><g font-family="system-ui,sans-serif" font-size="16" font-weight="650" fill="#182c35" style="paint-order:stroke;stroke:#fffef9;stroke-width:5px;stroke-linejoin:round"><text x="113" y="314">(−2, −3)</text><text x="281" y="340">(0, −4)</text><text x="326" y="169">(2, 3)</text><text x="414" y="119">(5, 4)</text><text x="450" y="422" fill="${A}">A</text><text x="469" y="80" fill="${B}">B</text></g></svg><figcaption>Redrawn from the textbook’s labeled coordinates. The highlighted line is the one you are finding the slope of.</figcaption></figure>`;
}



function referenceHtml(){return `<p>Use this sheet while you work. It lists methods, not the answer key.</p><div class="reference-grid">
 <div class="reference-item"><h4>Square of a sum</h4>${math('(u + v)<sup>2</sup> = u<sup>2</sup> + 2uv + v<sup>2</sup>')}<p>First square, twice the product, last square.</p></div>
 <div class="reference-item"><h4>Square of a difference</h4>${math('(u − v)<sup>2</sup> = u<sup>2</sup> − 2uv + v<sup>2</sup>')}<p>The middle is negative; the last square is positive.</p></div>
 <div class="reference-item"><h4>Factoring perfect squares</h4>${math('u<sup>2</sup> ± 2uv + v<sup>2</sup> = (u ± v)<sup>2</sup>')}<p>Check the middle term before assuming a perfect square.</p></div>
 <div class="reference-item"><h4>Exponent rules</h4>${math('x<sup>m</sup>x<sup>n</sup> = x<sup>m+n</sup><br>(x<sup>m</sup>)<sup>n</sup> = x<sup>mn</sup>')}<p>A power of a product applies to every factor.</p></div>
 <div class="reference-item"><h4>Scientific notation</h4>${math('a × 10<sup>n</sup>')}<p>1 ≤ |a| &lt; 10; n is an integer. A tiny positive decimal has a negative exponent.</p></div>
 <div class="reference-item"><h4>Distance</h4>${math('d = '+root('(Δx)<sup>2</sup> + (Δy)<sup>2</sup>'))}<p>Subtract coordinates in matching order. Distance is nonnegative.</p></div>
 <div class="reference-item"><h4>Circle</h4>${math('(x − h)<sup>2</sup> + (y − k)<sup>2</sup> = r<sup>2</sup>')}<p>Center (h, k); radius r. Take the square root of the right side.</p></div>
 <div class="reference-item"><h4>Slope</h4>${math('m = '+frac('y<sub>2</sub> − y<sub>1</sub>','x<sub>2</sub> − x<sub>1</sub>'))}<p>Horizontal: y = c, m = 0. Vertical: x = c, slope undefined.</p></div>
 <div class="reference-item"><h4>Solving equations</h4><p>Balance both sides. Clear fractions. Isolate a radical before squaring and check the original equation. When solving u² = k, consider ±√k where real and defined.</p></div>
 <div class="reference-item"><h4>Round-trip travel</h4>${math('v<sub>out</sub>t = v<sub>back</sub>(T − t)')}<p>Same route → same distance. Return time is total time minus outward time.</p></div></div>`;}



function freshCustomState(){return{lab:{sign:-1,a:4}};}
function normalizeCustomState(raw){
 const source=raw?.lab||raw?.custom?.lab||{};
 return{lab:{sign:source.sign===1?1:-1,a:Number.isInteger(source.a)&&source.a>=1&&source.a<=8?source.a:4}};
}
function patternLabHTML(state){
 const lab=state.custom?.lab||{sign:-1,a:4},a=lab.a,sign=lab.sign,s=sign===1?'+':'−';
 return `<section class="lab"><div class="eyebrow">Pattern lab · try both signs</div><div class="lab-controls"><div class="segmented" role="group" aria-label="Sign inside the binomial"><button data-action="lab-sign" data-value="1" class="${sign===1?'selected':''}">+</button><button data-action="lab-sign" data-value="-1" class="${sign===-1?'selected':''}">−</button></div><div class="range-wrap"><label for="lab-number">Second term: <strong>${a}</strong></label><input type="range" id="lab-number" min="1" max="8" step="1" value="${a}"></div></div><table class="product-table"><caption>Signed entries are algebraic products.</caption><thead><tr><th>×</th><th>x</th><th>${s} ${a}</th></tr></thead><tbody><tr><th>x</th><td>x<sup>2</sup></td><td class="middle">${s} ${a===1?'':a}x</td></tr><tr><th>${s} ${a}</th><td class="middle">${s} ${a===1?'':a}x</td><td>+ ${a*a}</td></tr></tbody></table><div class="lab-result">(x ${s} ${a})<sup>2</sup> = x<sup>2</sup> ${s} ${2*a}x + ${a*a}</div></section>`;
}
function mountTopicExtras(rootEl,state){
 const node=rootEl.querySelector('#pattern-lab');if(node)node.innerHTML=patternLabHTML(state);
}
function handleAction(action,el,state,api){
 if(action!=='lab-sign')return false;
 state.custom=state.custom||freshCustomState();state.custom.lab=state.custom.lab||freshCustomState().lab;state.custom.lab.sign=Number(el.dataset.value)===1?1:-1;api.save();api.render();return true;
}
function handleInput(el,state,api){
 if(el.id!=='lab-number')return false;
 state.custom=state.custom||freshCustomState();state.custom.lab=state.custom.lab||freshCustomState().lab;state.custom.lab.a=Math.max(1,Math.min(8,Number(el.value)||4));api.save();const node=document.querySelector('#pattern-lab');if(node)node.innerHTML=patternLabHTML(state);return true;
}
function renderQuestionAsset(q){return q.graph?graphSVG(q.graph):'';}

function sourceMatches(raw){
 if(!raw?.source)return true;
 const src=raw.source;
 for(const key of Object.keys(DEFAULT_SOURCE)){
  if(!src[key])return false;
  for(const field of Object.keys(DEFAULT_SOURCE[key]).filter(k=>k!=='confirmed'))if(src[key][field]!==DEFAULT_SOURCE[key][field])return false;
 }
 return true;
}
function migrateStandalone(raw,api){
 if(!raw||!['1.0.0','1.1.0','1.2.0'].includes(raw.version))throw Error('Unsupported standalone Lesson 89 progress version.');
 if(raw.version!=='1.0.0' && raw.sourceRevision && raw.sourceRevision!=='lesson89-2026-10-02-closeups')throw Error('The standalone file uses a different Lesson 89 source edition.');
 if(raw.version!=='1.0.0' && !sourceMatches(raw))throw Error('The standalone file does not match the confirmed Lesson 89 source values.');
 const copy=JSON.parse(JSON.stringify(raw));
 if(raw.version==='1.0.0'){
  copy.answers=copy.answers||{};
  delete copy.answers['s-11'];delete copy.answers['s-12'];
  if(!sourceMatches(raw))delete copy.answers['s-16'];
 }
 copy.lessonId='lesson-089';
 copy.topicIndex=Number.isInteger(copy.lessonIndex)?copy.lessonIndex:0;
 copy.custom={lab:copy.lab||{sign:-1,a:4}};
 const state=api.normalizeLessonState(packageDef,copy);
 const reset=raw.version==='1.0.0'?['#11','#12',...(!sourceMatches(raw)?['#16']:[])]:[];
 state.migration={from:`standalone-${raw.version}`,at:new Date().toISOString(),message:raw.version==='1.0.0'?`Imported from standalone Lesson 89 v1.0. Source-corrected exercises ${reset.join(', ')} were reopened; unaffected attempts and notes were retained.`:`Imported from standalone Lesson 89 v${raw.version}. Attempt history was retained and re-evaluated under the shared course scoring policy.`};
 return state;
}

const packageDef={
 id:'lesson-089',
 number:89,
 chapter:'Chapter 12',
 title:'Standard Forms',
 contentVersion:'course-package-1.0',
 sourceRevision:'lesson89-2026-10-02-closeups',
 heroTitle:'Spot the pattern.<br><em>Simplify the work.</em>',
 description:'Make sense of binomial squares, build your algebra toolkit, and work through every included exercise at your own pace and in any order.',
 heroArt:`<div class="art-caption"><span>A small pattern</span><span>A powerful shortcut</span></div><div class="formula">(x + a)<sup>2</sup> = x<sup>2</sup> + 2ax + a<sup>2</sup></div><div class="connector">↕</div><div class="formula">(x − a)<sup>2</sup> = x<sup>2</sup> − 2ax + a<sup>2</sup></div><p class="art-foot">The middle term is twice the product.<br>The sign makes the difference.</p>`,
 topics,
 sections:[
  {id:'practice',label:'Practice 89',intro:'Five exercises on factoring, expanding, rearranging a formula, and translating a travel problem.'},
  {id:'problem',label:'Problem Set 89',intro:'The 21 review exercises, from standard forms and scientific notation to geometry, equations, slope, and travel time.'}
 ],
 buildQuestions,
 referenceHtml,
 freshCustomState,
 normalizeCustomState,
 mountTopicExtras,
 handleAction,
 handleInput,
 renderQuestionAsset,
 migrateStandalone,
 sourceStatus:{pages:'433–436',verified:'2026-10-02 close-ups',uncertainItems:[]}
};
global.Algebra2CourseRegistry.register(packageDef);
})(window);
